development:
    adapter: postgresql
    encoding: unicode
    host: localhost
    database: thinkdifferent_development
    username: triton
    password:

test:
    adapter: postgresql
    encoding: unicode
    host: localhost
    database: thinkdifferent_test
    username: triton
    password:
